directories:
  output: builds
  buildResources: build
appId: com.diplomkey.app
files:
  - filter:
      - src/**/*
      - '!node_modules'
win:
  target: nsis
  icon: build/icon.ico
asar: false
electronVersion: 27.0.2
